### ISSUE TITLE
Typescript Rewrite

### ISSUE THREAD

**Issue by alex20465** [alex20465/deskbluez#10]

**Comment by darkkatarsis** [comment]
Hey, I see that you have started work on a new version of deskbluez. If I can help somehow, let me know. Ps. There is a chance to add a MQTT client as in the previous version?

**Comment by alex20465** [comment]
@darkkatarsis Yes I will do it as an additional package, I will be thankful if you could test new releases and open issues. Thanks @darkkatarsis.
