### ISSUE TITLE
docker container

### ISSUE THREAD

**Issue by theskyisthelimit** [alex20465/deskbluez#17]
Hello

This is exactly what I was looking for. 

Is it possible to run deskbluez inside a docker container?

**Comment by alex20465** [comment]
Its possible if you are able to passthrough the bluetooth device to the container, yes it should be possible.

**Comment by maxime1992** [comment]
@theskyisthelimit have you found anything? Could you share it please? :) 

Maybe we'd like to achieve the same: I'd like to build a tiny add-on for home assistant. So I need somehow to be able to run this on Docker.

I've found this thread: https://stackoverflow.com/questions/28868393/accessing-bluetooth-dongle-from-inside-docker/36865509 but I'm wondering if you managed to do this without using the --privilege argument

**Comment by theskyisthelimit** [comment]
Hi @maxime1992 

I'm using [this tool](https://apps.apple.com/ch/app/desk-remote-control/id1509037746) to move my table with NFC Tags & Siri Shortcuts.

For another project I was able to use bluetooth with Homeassistant whith the --privilege argument. Not sure if it works without.
