### ISSUE TITLE
Compatibility with Linak DPG1C

### ISSUE THREAD

**Issue by darkkatarsis** [alex20465/deskbluez#2]
I was able to connect to my desk, unfortunately only the desk position works fine.
Could you help me a little or direct me where to look for the problem?

<img width="477" alt="Screenshot 2020-05-31 at 00 20 04" src="https://user-images.githubusercontent.com/24244919/83340101-8b2d7500-a2d4-11ea-8517-38ab27d84036.png">

"move --to " do nothing

**Comment by darkkatarsis** [comment]
Ok, it started working. I don't know what has changed. I think other paired devices may have interrupted the operation.

I am able to pick up items via mqtt, but I don't quite understand how to construct the topic "control" to be able to control the desk. Something like this ?

topic: control
payload: "up" ?

<img width="1024" alt="Screenshot 2020-05-31 at 12 50 46" src="https://user-images.githubusercontent.com/24244919/83350591-64575900-a33d-11ea-9b0b-eb9c29bab0a6.png">

or maybe it should be some kind json ?

**Comment by adidoes** [comment]
Try the payload without the quotes

**Comment by darkkatarsis** [comment]
Yes that was it, I found the reason when I started debugging the code. Now everything works. Thank you for your interest and help.

Everything works perfect but i found another problem and it seems I’m not the only one (may only apply to devices DPG1C). After some time of inactivity [or when the BT connection is broken], I can see the current position of the desk, but am unable to control it. The only way to regain control is to reconnect and re-save the “favourite” position via 3rd-party app. (e.g. Desk Assistant). Then I can connect again with deskbluez and suddenly everything goes back to normal operation. 

<img width="1550" alt="Screenshot 2020-06-03 at 07 42 18" src="https://user-images.githubusercontent.com/24244919/83601217-710fc300-a570-11ea-828a-c3cf69acf5b2.png">

![Screen-Recording-2020-06-02-at-0](https://user-images.githubusercontent.com/24244919/83602253-7a019400-a572-11ea-829b-359010f2a6f8.gif)


Do you have any idea?

**Comment by bradstcroix** [comment]
I'm having the same issue. Did you ever get it resolved?

**Comment by darkkatarsis** [comment]
No, I think the DPG1C model goes to sleep and needs to be woken up after some time. Unfortunately, I lack the knowledge to solve this problem.

**Comment by bradstcroix** [comment]
I grabbed a frame dump from the Android Desk Control app and have looked at in Wireshark. It seems there are some other commands being sent to the DPG1C by the official app after it pairs. One of which is a move request, before the actual command is issued. I think that might have something to do with why we can't get the desk moving after connecting to it using Deskbluez on it's own. It's like the official app 'warms it up' so to speak by putting it in a state to accept the move commands. That's just a hunch btw. I will attempt to test some more and see what I can find

**Comment by darkkatarsis** [comment]
Would be great. I was browsing other projects on git looking for a solution. Unfortunately, very few people use the latest linak module. In the meantime, I made some improvements on my fork. I added more and clean data to MQTT and a systemctl service that starts after each restart.

<img width="893" alt="Screenshot 2020-08-15 at 13 13 01" src="https://user-images.githubusercontent.com/24244919/90311293-a84c0a00-def9-11ea-834b-fe832ce557fc.png">
<img width="545" alt="Screenshot 2020-08-15 at 13 13 14" src="https://user-images.githubusercontent.com/24244919/90311294-ab46fa80-def9-11ea-8354-dfa4f08c151b.png">

**Comment by alex20465** [comment]
Thank you very much darkkatarsis, I am in vacation right now, I will look into it once i am back

**Comment by darkkatarsis** [comment]
@bradstcroix did you find something?

**Comment by bradstcroix** [comment]
@darkkatarsis haven't had time to do another Wireshark session with it yet. As a workaround I've written a flow in Node-Red that keeps the connection alive using MTTQ commands. I've found that you have to send it a move command once every 3 hours or so to keep it from sleeping. The flow I use detects the timestamp of last move command sent then sends an up/down command after 3 hours. Not elegant but has kept the connection alive for a week so far.

As I said earlier I believe there's a move request (not command) that will keep it alive without moving it which will initialise it. Will need to find some time to test. 

Cheers

**Comment by darkkatarsis** [comment]
In fact, I did similar automation. Sending a position change every 3 hours from the last position, actually maintains the connection and does not block the control. Weird

**Comment by darkkatarsis** [comment]
https://github.com/anson-vandoren/linak-desk-spec/blob/6c5bd06325612f2c0667d1c6e3ee83d717758701/spec.md

**Comment by bradstcroix** [comment]
Nice find

**Comment by darkkatarsis** [comment]
@alex20465 maybe you can help me. After connecting to MQTT broker, the desk changes its position to last value of subscribeTopic. Do you have any idea how to block this behavior? So that the connection does not activate the change of position immediately? Need to clear some cache? Overwriting the subscribeTopic as null right after the connection doesn't help either

Edit: Nevermind, I had to restart the broker :)

**Comment by alex20465** [comment]
@darkkatarsis It would be nice if you open a new issue with more details about how you connect and what exactly you subscribe. I will start a new release with improved reliability regarding the connection and miss-behaviors.

**Comment by darkkatarsis** [comment]
There is new issue related to this topic:
Duplicate of #7

**Comment by darkkatarsis** [comment]
> @darkkatarsis It would be nice if you open a new issue with more details about how you connect and what exactly you subscribe. I will start a new release with improved reliability regarding the connection and miss-behaviors.

Still planning on working on a new version?

**Comment by Kwull** [comment]
@darkkatarsis, can you share the link to Desk Assistant MacOS app? BTW, have you tested deskbluez under Mac?

**Comment by darkkatarsis** [comment]
Yes, I use my MacBook every day :)
Sure https://apps.apple.com/tt/app/desk-remote-control/id1509037746?mt=12

**Comment by rmervine** [comment]
@darkkatarsis, is there some kind of trick you done to get this to pair with the DPG1C controller? From looking online, it looks like a couple of us use it. I have it and I tried many of the apps out there to try and control this with the ultimate goal of controlling in HA. 

I'm getting "Authentication Failed" when trying to pair the controller through this app. Just curious if you had the same issue or not. I'm also using a Raspberry Pi for this experiment.
