### ISSUE TITLE
E16 Error on Linak DPG1C

### ISSUE THREAD

**Issue by bradstcroix** [alex20465/deskbluez#6]
Managed to get the software working in Ubuntu 20.4 to the point I can run the Position command to successfully retrieve the desk position.

However, when I attempt a move-to command, the command hangs in the terminal and desk does nothing. I've observed that when manually trying to lower the desk after this, there's an E16 error displayed on the desk controller LCD.

Linak specifies this error in their troubleshooting guide as:

Key Error » Illegal keys pressed (handled internally in DP1C).
Possible Cause » Hitting multiple buttons simultaneously
Solution » Check desk panel

If I ctrl-c to terminate the process in the terminal, the error dissapears.

Any ideas?

Thanks

**Comment by darkkatarsis** [comment]
The error occurs when several commands are given at the same time. For example, with applications and manually. Its normal
