### ISSUE TITLE
Communication problem with the DPG1C module

### ISSUE THREAD

**Issue by darkkatarsis** [alex20465/deskbluez#7]
The version I will describe is the one from your repository. I run the applications in MQTT mode on Raspberry Pi Zero W. I’m only subscribing topic with the change of position. After connection, the DPG1C controller works smoothly until there is a 2-3 hour break between sending the last position change. After this time, the controller stops responding to commands. And a connection error pops up.

<img width="1550" alt="screen" src="https://user-images.githubusercontent.com/24244919/92102240-a4b3f080-edde-11ea-8580-b793223a824a.png">
Notes to the screen:

- disconnecting and reconnecting the bluetooth on Raspberry Pi Zero does not help
- shutting down deskbluez app and starting it does not help either

Which helps:
Connecting to a desk with another application, e.g. dedicated to MacOS - “Desk Remote Control”. The control of the desk is still blocked unless you click “save favorite position”. Saving the position removes the desk control lock, and I can re-pair and control my desk again using deskbluez.

![film](https://user-images.githubusercontent.com/24244919/92102329-beedce80-edde-11ea-9de2-f842a9af051d.gif)

General comments:

- Disconnecting and connecting the desk every 2h-3h without changing position - does not help
- Downloading the current position and subscribing after 2h-3h to overwrite - does not help
- It is possible that a change of position every 2-3h by +1cm/-1cm keeps the connection (unfortunately; as a result, the desk vibrates every 2-3h), and this is rather a wrong solution. 
- There may be a Bluetooth command that sustains communication/authentication, but I am not aware of any.

**Comment by darkkatarsis** [comment]
@alex20465 Just like you asked, I've set up a new issue. The description is understandable enough? Can I still help?

**Comment by michalzadkowski** [comment]
Same here. Any help would be appreciated.

**Comment by maxime1992** [comment]
@darkkatarsis I believe I'm trying to achieve exactly what you've done.
Creating a tiny server which will handle the connection between the desk in bluetooth and with home assistant using MQTT.

Have you had any luck on this path since? I've been banging my head on this...

**Comment by darkkatarsis** [comment]
Unfortunately no, the library responsible for the bt connection is unstable - at least for DPG1C. Ultimately, I use Desk Remote Control from app store (I added a few keyboard shortcuts). Worth to know that shortcuts can be automated later, for example using Automator from apple and ssh from HA.
